import Foundation

/// Every placeholder and filter with a description, for the editor's Insert menu,
/// reference and autocomplete (SPEC §5.3.3, §5.3.6). Pure data.
enum PlaceholderCatalog {
    struct Entry: Identifiable, Equatable, Sendable {
        enum Kind: Sendable {
            case placeholder
            case filter
        }

        var kind: Kind
        /// The placeholder or filter name, e.g. `date` or `default`.
        var name: String
        /// What gets inserted: `{{date:YYYY-MM-DD}}` for a placeholder, `|default:""` for a filter.
        var insertText: String
        var summary: String
        /// Generated by the on-device model.
        var isAI = false

        var id: String { "\(kind)-\(name)" }
    }

    static let placeholders: [Entry] = [
        .init(kind: .placeholder, name: "title", insertText: "{{title}}",
              summary: "AI title if AI titles are on, otherwise “Voice note” and the time"),
        .init(kind: .placeholder, name: "project", insertText: "{{project}}", summary: "Project name"),
        .init(kind: .placeholder, name: "type", insertText: "{{type}}",
              summary: "Note type you picked. With Auto, the AI-chosen type if classification is on"),
        .init(kind: .placeholder, name: "date", insertText: "{{date}}",
              summary: "Recording date, YYYY-MM-DD. Custom: {{date:dddd D MMMM YYYY}}"),
        .init(kind: .placeholder, name: "time", insertText: "{{time}}", summary: "Recording start time, HH:mm"),
        .init(kind: .placeholder, name: "datetime", insertText: "{{datetime}}",
              summary: "Date and time: YYYY-MM-DDTHH:mm:ss (Obsidian) or ISO 8601 (standard)"),
        .init(kind: .placeholder, name: "weekday", insertText: "{{weekday}}", summary: "Day of the week, e.g. Friday"),
        .init(kind: .placeholder, name: "duration", insertText: "{{duration}}", summary: "Recording length, e.g. 3m12s"),
        .init(kind: .placeholder, name: "duration_seconds", insertText: "{{duration_seconds}}",
              summary: "Recording length in whole seconds"),
        .init(kind: .placeholder, name: "locale", insertText: "{{locale}}", summary: "Transcription language, e.g. en-GB"),
        .init(kind: .placeholder, name: "filename", insertText: "{{filename}}", summary: "Note filename without .md"),
        .init(kind: .placeholder, name: "processing", insertText: "{{processing}}",
              summary: "tidied, tidied-partial or raw"),
        .init(kind: .placeholder, name: "app_version", insertText: "{{app_version}}", summary: "Murmur's version"),
        .init(kind: .placeholder, name: "ai_summary", insertText: "{{ai_summary}}",
              summary: "One or two sentence summary", isAI: true),
        .init(kind: .placeholder, name: "ai_key_points", insertText: "{{ai_key_points}}",
              summary: "List of key points", isAI: true),
        .init(kind: .placeholder, name: "ai_tags", insertText: "{{ai_tags}}",
              summary: "List of tags, following the AI tag rules", isAI: true),
    ]

    static let filters: [Entry] = [
        .init(kind: .filter, name: "lower", insertText: "|lower", summary: "lowercase"),
        .init(kind: .filter, name: "upper", insertText: "|upper", summary: "UPPERCASE"),
        .init(kind: .filter, name: "slug", insertText: "|slug", summary: "lowercase-with-dashes, for filenames"),
        .init(kind: .filter, name: "wikilink", insertText: "|wikilink", summary: "Wraps as [[…]]"),
        .init(kind: .filter, name: "quote", insertText: "|quote", summary: "Always double-quoted"),
        .init(kind: .filter, name: "flow", insertText: "|flow", summary: "List on one line: [a, b]"),
        .init(kind: .filter, name: "block", insertText: "|block", summary: "List with one - item per line"),
        .init(kind: .filter, name: "first", insertText: "|first", summary: "First item of a list"),
        .init(kind: .filter, name: "default", insertText: "|default:\"\"", summary: "Text to use when the value is empty"),
    ]

    static var all: [Entry] { placeholders + filters }
}
